import Head from 'next/head';
import { useFetch } from '../hooks/useFetch';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { data, loading, error } = useFetch('/api/posts');

  if (error) return <div>An error occured.</div>;
  if (loading) return <div>Loading ...</div>;

  return (
    <>
      <Head>
        <title>Piotr Doniak</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <div className="flex h-full items-center justify-center">
          <div>
            <h1 className="mb-4 text-4xl font-bold">Hello World!</h1>
            <div>
              {data?.posts.length !== 0 && (
                <ul className="space-y-4">
                  {data?.posts.map((post) => (
                    <li key={post.id} className="rounded bg-gray-200 p-4">
                      <div className="font-medium">{post.title}</div>
                      <div className="text-sm italic">{post.content}</div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
