import Head from 'next/head';
import useSWR from 'swr';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const fetcher = (...args) => fetch(...args).then((res) => res.json());

  const { data, error } = useSWR('/api/posts', fetcher);
  if (error) return <div>An error occured.</div>;
  if (!data) return <div>Loading ...</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <div className="flex items-center justify-center h-full">
          <div>
            <h1 className="text-4xl font-bold mb-4">Hello World!</h1>
            <div>
              {data.posts.length !== 0 && (
                <ul className="space-y-4">
                  {data.posts.map((post) => (
                    <li key={post.id} className="bg-gray-200 rounded p-4">
                      <div className="font-medium">{post.title}</div>
                      <div className="text-sm italic">{post.content}</div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
