import Head from 'next/head';
import Link from 'next/link';
import Characters from '@/components/Characters';

export default function Post({ data }) {
  return (
    <>
      <Head>
        <title>Post - Piotr Doniak</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-xl">
        <div className="mt-10 w-full">
          <div>
            <Link href="/">
              <div className="text-blue-500">Go to home</div>
            </Link>
            <h1 className="mb-4 text-4xl font-bold">Characters</h1>
            <Characters data={data} />
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // eslint-disable-next-line no-promise-executor-return
  const delay = (s: number) => new Promise((resolve) => setTimeout(resolve, s));
  const res = await fetch('https://rickandmortyapi.com/api/character');
  await delay(2000);
  const data = await res.json();

  return {
    props: { data },
  };
}
